-- AlterTable
ALTER TABLE "Cryptocurrency" ALTER COLUMN "market_cap" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fully_diluted_valuation" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_volume" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "market_cap_change_24h" SET DATA TYPE DOUBLE PRECISION;
